### ISSUE TITLE
评论系统添加记 - xf67

### ISSUE THREAD

**Issue by xf67** [xf67/xf67.github.io#2]
https://xf67.github.io/2021/12/04/%E8%AF%84%E8%AE%BA%E6%B7%BB%E5%8A%A0%E8%AE%B0/ 

 今晚的月色很美,

**Comment by xf67** [comment]
**好耶**

**Comment by xf67** [comment]
但是gitalk大大拖慢了加载速度，以后空了一定要把好一点的评论系统装上去。

**Comment by hzyangjc** [comment]
### 针不戳
